[versions]
kotlin = "2.3.0"
ksp = "2.3.0"
intellij = "2.9.0"
jimmer = "0.9.119"
byteBuddy = "1.17.1"
kotlinpoet = "2.0.0"
javapoet = "1.13.0"
antlr4IntellijAdaptor = "0.1"
antlr = "4.13.2"
changelog = "2.2.1"
h2 = "2.3.232"
gradleToolingExtension = "231.9423.9"
jackson = "2.19.2"
jspecify = "1.0.0"

[libraries]
jimmer-core = { module = "org.babyfish.jimmer:jimmer-core", version.ref = "jimmer" }
jimmer-sql = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
jimmer-apt = { module = "org.babyfish.jimmer:jimmer-apt", version.ref = "jimmer" }
jimmer-ksp = { module = "org.babyfish.jimmer:jimmer-ksp", version.ref = "jimmer" }
jimmer-dto-compiler = { module = "org.babyfish.jimmer:jimmer-dto-compiler", version.ref = "jimmer" }
jimmer-spring-boot-starter = { module = "org.babyfish.jimmer:jimmer-spring-boot-starter", version.ref = "jimmer" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byteBuddy" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
antlr4-intellij-adaptor = { module = "org.antlr:antlr4-intellij-adaptor", version.ref = "antlr4IntellijAdaptor" }
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
gradle-tooling-extension = { module = "com.jetbrains.intellij.gradle:gradle-tooling-extension", version.ref = "gradleToolingExtension" }
jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
intellij-platform = { module = "org.jetbrains.intellij.platform:org.jetbrains.intellij.platform.gradle.plugin", version.ref = "intellij" }
changelog = { module = "org.jetbrains.changelog:org.jetbrains.changelog.gradle.plugin", version.ref = "changelog" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }